apiVersion: mariadb.mmontes.io/v1alpha1
kind: SqlJob
metadata:
  name: sqljob
spec:
  mariaDbRef:
    name: mariadb
  schedule:
    cron: "*/1 * * * *"
    suspend: false
  username: mariadb
  passwordSecretKeyRef:
    name: mariadb
    key: password
  database: mariadb
  sql: |
    CREATE TABLE IF NOT EXISTS users (
      id bigint PRIMARY KEY AUTO_INCREMENT,
      username varchar(255) NOT NULL,
      UNIQUE KEY name__unique_idx (username)
    );
    INSERT INTO users(username) VALUES('mmontes11') 
      ON DUPLICATE KEY UPDATE id=id;
    CREATE TABLE IF NOT EXISTS repos (
      id bigint PRIMARY KEY AUTO_INCREMENT,
      name varchar(255) NOT NULL,
      owner_id bigint NOT NULL,
      UNIQUE KEY name__unique_idx (name),
      FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE
    );
    INSERT INTO repos(name, owner_id) VALUES('mariadb-operator', (SELECT id FROM users WHERE username = 'mmontes11'))
      ON DUPLICATE KEY UPDATE id=id;
    INSERT INTO repos(name, owner_id) VALUES('mariadb-operator-helm', (SELECT id FROM users WHERE username = 'mmontes11'))
      ON DUPLICATE KEY UPDATE id=id;
    INSERT INTO repos(name, owner_id) VALUES('mariadb-ha-poc', (SELECT id FROM users WHERE username = 'mmontes11'))
      ON DUPLICATE KEY UPDATE id=id;